version: '3.8'

networks:
  traefik:
    external: true

services:
  treafik:
    image: traefik:v2.10
    container_name: traefik
    # command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config/traefik.yml:/etc/traefik/traefik.yml
      - $PWD/proxy:/proxy
    restart: always
    networks:
      - traefik