# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.dd.f28.dev`)"

  file:
    directory: /proxy
    watch: true

# API and dashboard configuration
api:
  # insecure: true
  dashboard: true

## Static configuration
entryPoints:
  web:
    address: ":80"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

certificatesResolvers:
  myresolver:
    # Enable ACME (Let's Encrypt): automatic SSL.
    acme:

      # Email address used for registration.
      #
      # Required
      #
      email: "info@f28.nl"

      # File or key used for certificates storage.
      #
      # Required
      #
      storage: "/etc/traefik/acme/acme.json"